version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "getExtraOrbitFilesV2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vz4ek90c2d12"
s3_prefix = "getExtraOrbitFilesV2"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["getExtraOrbitFilesV2=317976261112.dkr.ecr.eu-west-2.amazonaws.com/mjmm-repo1"]
