---
- hosts: ukmonhelper
  gather_facts: no
  tasks:
  - name: import variables 
    include_vars: ./vars.yml
  - name: Ensures {{windestdir}} exists
    file: path={{windestdir}} state=directory  
    delegate_to: localhost
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    delegate_to: localhost
    with_items:
    - {src: '{{winsrcdir}}/checkLastLogin.ps1', dest: '{{windestdir}}/', mode: '754', backup: yes, directory_mode: no }
    - {src: '{{winsrcdir}}/dailyReportUserAdd.ps1', dest: '{{windestdir}}/', mode: '754', backup: yes, directory_mode: no }
    - {src: '{{winsrcdir}}/StationMaint.ps1', dest: '{{windestdir}}/', mode: '754', backup: yes, directory_mode: no }
    - {src: '{{winsrcdir}}/stationMaint2.py', dest: '{{windestdir}}/', mode: '644', backup: yes, directory_mode: no }
    - {src: '{{winsrcdir}}/testkeys.py', dest: '{{windestdir}}/', mode: '644', backup: yes, directory_mode: no }
    - {src: '{{winsrcdir}}/camTable.py', dest: '{{windestdir}}/', mode: '644', backup: yes, directory_mode: no }
    - {src: '{{winsrcdir}}/requirements.txt', dest: '{{windestdir}}/', mode: '644', backup: yes, directory_mode: no }
