---
- hosts: localhost
  vars:
    srcdir: /mnt/e/dev/meteorhunting/UKmon-shared
  tasks:
    - name: import dev variables 
      include_vars: ./dev-vars.yml
      tags: dev
    - name: import prod variables
      include_vars: ./prod-vars.yml
      tags: prod
    - name: sync to S3
      tags: [dev,prod]
      s3_sync:
        bucket: "{{ websitebucket }}"
        file_root: "{{ srcdir }}/archive/static_content/"
        #key_prefix: "/"
        permission: "bucket-owner-full-control"
        region: "eu-west-2"
        mode: push
    - name: Copy searchdialog to s3
      tags: [dev,prod]
      aws_s3:
        #aws_access_key: "{{ lookup('env','aws_key') }}"
        #aws_secret_key: "{{ lookup('env','aws_secret') }}"
        bucket: "{{ websitebucket }}"
        src: "{{srcdir}}/archive/website/templates/searchdialog-{{env}}.js"
        object: "/data/searchdialog.js"
        region: "eu-west-2"
        permission: "bucket-owner-full-control"
        mode: put
        overwrite: "true"
  