---
- hosts: ukmonhelper
  vars:
    srcdir: /mnt/e/dev/meteorhunting/UKMON-shared
  tasks:
  - name: import dev variables 
    include_vars: ./dev-vars.yml
    tags: dev
  - name: import prod variables
    include_vars: ./prod-vars.yml
    tags: prod
  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/R exists
    file: path={{destdir}}/R state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/logs exists
    file: path={{destdir}}/logs state=directory  
  - name: Ensures {{destdir}}/metrics exists
    file: path={{destdir}}/metrics state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/reports/ exists
    file: path={{destdir}}/data/reports/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/ exists
    file: path={{destdir}}/data/browse/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/annual/ exists
    file: path={{destdir}}/data/browse/annual/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/daily/ exists
    file: path={{destdir}}/data/browse/daily/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/monthly/ exists
    file: path={{destdir}}/data/browse/monthly/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/showers/ exists
    file: path={{destdir}}/data/browse/showers/ state=directory  
    tags: [dev,prod]
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    with_items:
    - {src: '{{srcdir}}/ukmon_pylib/', dest: '{{destdir}}/ukmon_pylib/', mode: '644', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/analysis/', dest: '{{destdir}}/analysis/', mode: '754', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/cronjobs/', dest: '{{destdir}}/cronjobs/', mode: '754', backup: no, directory_mode: yes }

    - {src: '{{srcdir}}/archive/costs/getMetrics.sh', dest: '{{destdir}}/costs/', mode: '754', backup: no }
    - {src: '{{srcdir}}/analysis/orbitSolver/reduceOrbit.sh', dest: '{{destdir}}/orbits/', mode: '744', backup: no }
    