---
- hosts: ukmonhelper
  vars:
    srcdir: /mnt/e/dev/meteorhunting/UKMON-shared
  tasks:
  - name: import dev variables 
    include_vars: ./dev-vars.yml
    tags: dev
  - name: import prod variables
    include_vars: ./prod-vars.yml
    tags: prod
  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/R exists
    file: path={{destdir}}/R state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/logs exists
    file: path={{destdir}}/logs state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/reports/ exists
    file: path={{destdir}}/data/reports/ state=directory  
    tags: [dev,prod]
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    with_items:
    - {src: '{{srcdir}}/ukmon_pylib/reports/cameraStatusReport.py', dest: '{{destdir}}/ukmon_pylib/reports/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/reports/createSearchableFormat.py', dest: '{{destdir}}/ukmon_pylib/reports/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/fileformats/imoWorkingShowerList.py', dest: '{{destdir}}/ukmon_pylib/fileformats/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/fileformats/UAFormats.py', dest: '{{destdir}}/ukmon_pylib/fileformats/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/fileformats/RMSFormats.py', dest: '{{destdir}}/ukmon_pylib/fileformats/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/fileformats/CameraDetails.py', dest: '{{destdir}}/ukmon_pylib/fileformats/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/fileformats/ReadUFOAnalyzerXML.py', dest: '{{destdir}}/ukmon_pylib/fileformats/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/converters/RMStoUFOA.py', dest: '{{destdir}}/ukmon_pylib/converters/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/converters//UFOAtoFTPdetect.py', dest: '{{destdir}}/ukmon_pylib/converters/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/utils/sendAnEmail.py', dest: '{{destdir}}/ukmon_pylib/utils/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/utils/getActiveShowers.py', dest: '{{destdir}}/ukmon_pylib/utils/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/utils/makeCoverageMap.py', dest: '{{destdir}}/ukmon_pylib/utils/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/reports/makeReportTables.py', dest: '{{destdir}}/ukmon_pylib/reports/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/reports/findFireballs.py', dest: '{{destdir}}/ukmon_pylib/reports/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/traj/ufoShowerAssoc.py', dest: '{{destdir}}/ukmon_pylib/traj/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/traj/ufoTrajSolver.py', dest: '{{destdir}}/ukmon_pylib/traj/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/traj/reportOfLatestMatches.py', dest: '{{destdir}}/ukmon_pylib/traj/', mode: '644', backup: no }
    - {src: '{{srcdir}}/ukmon_pylib/traj/extraDataFiles.py', dest: '{{destdir}}/ukmon_pylib/traj/', mode: '644', backup: no }

    - {src: '{{srcdir}}/archive/reports/runMatching.sh', dest: '{{destdir}}/analysis/', mode: '754', backup: no }
    - {src: '{{srcdir}}/archive/cronjobs/nightlyJob.sh', dest: '{{destdir}}/cronjobs/', mode: '754', backup: no }
    - {src: '{{srcdir}}/archive/cronjobs/getImoWSfile.sh', dest: '{{destdir}}/cronjobs/', mode: '754', backup: no }
    - {src: '{{srcdir}}/archive/cronjobs/updateSearchIndex.sh', dest: '{{destdir}}/cronjobs/', mode: '754', backup: no }
    - {src: '{{srcdir}}/archive/reports/findAllMatches.sh', dest: '{{destdir}}/analysis/', mode: '744', backup: no }
    - {src: '{{srcdir}}/archive/reports/createSearchable.sh', dest: '{{destdir}}/analysis/', mode: '744', backup: no }
    - {src: '{{srcdir}}/archive/reports/convertUfoToRms.sh', dest: '{{destdir}}/analysis/', mode: '744', backup: no }
    - {src: '{{srcdir}}/archive/reports/monthlyReports.sh', dest: '{{destdir}}/analysis/', mode: '744', backup: no }
    - {src: '{{srcdir}}/archive/reports/runRAnalysis.sh', dest: '{{destdir}}/analysis/', mode: '744', backup: no }
    - {src: '{{srcdir}}/archive/reports/createReport.sh', dest: '{{destdir}}/analysis/', mode: '744', backup: no }
    - {src: '{{srcdir}}/archive/reports/reportYear.sh', dest: '{{destdir}}/analysis/', mode: '744', backup: no }
    - {src: '{{srcdir}}/archive/reports/templates/UA_header.txt', dest: '{{destdir}}/analysis/templates/', mode: '644', backup: no }
    - {src: '{{srcdir}}/archive/reports/templates/UO_header.txt', dest: '{{destdir}}/analysis/templates/', mode: '644', backup: no }
    - {src: '{{srcdir}}/archive/reports/templates/RMS_header.txt', dest: '{{destdir}}/analysis/templates/', mode: '644', backup: no }
    - {src: '{{srcdir}}/archive/reports/templates/report-template.html', dest: '{{destdir}}/analysis/templates/', mode: '644', backup: no }
    - {src: '{{srcdir}}/archive/reports/templates/shower-report-template.html', dest: '{{destdir}}/analysis/templates/', mode: '644', backup: no }
    - {src: '{{srcdir}}/archive/reports/addRMSShowerDets.sh', dest: '{{destdir}}/analysis/', mode: '744', backup: no }
    - {src: '{{srcdir}}/archive/reports/updateRMSShowerAssocs.sh', dest: '{{destdir}}/analysis/', mode: '744', backup: no }
    - {src: '{{srcdir}}/analysis/orbitSolver/reduceOrbit.sh', dest: '{{destdir}}/orbits/', mode: '744', backup: no }
    