- hosts: ukmonhelper
  vars:
    srcdir: /mnt/e/dev/meteorhunting/UKMON-shared/archive
  tasks:
  - name: import dev variables 
    include_vars: dev-vars.yml
    tags: dev
  - name: import prod variables
    include_vars: prod-vars.yml
    tags: prod
  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  
    tags: [dev,prod]

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    with_items:
    - {src: '{{srcdir}}/config.ini', dest: '{{destdir}}/config/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/.bashrc', dest: '/home/ec2-user', mode: '644', backup: yes }
    - {src: '{{srcdir}}/.bash_aliases', dest: '/home/ec2-user', mode: '644', backup: no }
    
  - name: update environment name
    lineinfile: 
      path: '{{destdir}}/config/config.ini'
      regexp: 'RUNTIME_ENV='
      line: 'RUNTIME_ENV={{env}}'
    tags: [dev,prod]
  - name: update mail recip
    lineinfile: 
      path: '{{destdir}}/config/config.ini'
      regexp: 'MAILRECIP='
      line: 'MAILRECIP=markmcintyre99@googlemail.com'
    tags: [dev,prod]
  - name: update id file
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'IDFILE='
      line: 'IDFILE=$HOME/.ssh/mjmm-data.key'
    tags: [dev,prod]
  - name: set input folder  
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'MATCHDIR='
      line: 'MATCHDIR=/home/ec2-user/ukmon-shared/matches'
    tags: [dev,prod]
  - name: update scripts folder
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'SRC='
      line: 'SRC={{destdir}}'
    tags: [dev,prod]
  - name: update templates folder
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'TEMPLATES='
      line: 'TEMPLATES={{destdir}}/website/templates'
    tags: [dev,prod]
  - name: update R code folder
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'RCODEDIR='
      line: 'RCODEDIR={{destdir}}/R'
    tags: [dev,prod]
  - name: update data folder
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'DATADIR='
      line: 'DATADIR={{destdir}}/data'
    tags: [dev,prod]
  - name: update RMS loc
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'RMS_LOC='
      line: 'RMS_LOC=/home/ec2-user/src/RMS'
    tags: [dev,prod]
  - name: update wmpl loc
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'WMPL_LOC='
      line: 'WMPL_LOC={{wmplhome}}'
    tags: [dev,prod]
  - name: update camera info file loc
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'CAMINFO='
      line: 'CAMINFO=/home/ec2-user/ukmon-shared/consolidated/camera-details.csv'
    tags: [dev,prod]
  - name: update archive files loc
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'ARCHDIR='
      line: 'ARCHDIR=/home/ec2-user/ukmon-shared/archive'
    tags: [dev,prod]
  - name: update website loc
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'WEBSITEBUCKET='
      line: 'WEBSITEBUCKET=s3://{{websitebucket}}'
    tags: [dev,prod]
  - name: update website aws key
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'WEBSITEKEY='
      line: 'WEBSITEKEY={{websitekey}}'
    tags: [dev,prod]
  - name: update Calcengine Server I
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'SERVERINSTANCEID='
      line: 'SERVERINSTANCEID={{calcinstance}}'
    tags: [dev,prod]
  - name: update config file loc
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'CONFIG='
      line: 'CONFIG={{destdir}}/config'
    tags: [dev,prod]
  - name: update site URL
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'SITEURL='
      line: 'SITEURL={{siteurl}}'
    tags: [dev,prod]
  - name: update mail host
    lineinfile: 
      path: '{{destdir}}/config/config.ini'
      regexp: 'MAILHOST='
      line: 'MAILHOST=smtp.gmail.com'
    tags: [dev,prod]
  - name: update mail port
    lineinfile: 
      path: '{{destdir}}/config/config.ini'
      regexp: 'MAILPORT='
      line: 'MAILPORT=587'
    tags: [dev,prod]
  - name: update mail user
    lineinfile: 
      path: '{{destdir}}/config/config.ini'
      regexp: 'MAILUSER='
      line: 'MAILUSER=mjmm456'
    tags: [dev,prod]
  - name: update mail pwd
    lineinfile: 
      path: '{{destdir}}/config/config.ini'
      regexp: 'MAILPWD='
      line: 'MAILPWD=~/.ssh/gmailpass'
    tags: [dev,prod]
  - name: update archive loc
    lineinfile:
      path: '{{destdir}}/config/config.ini'
      regexp: 'UKMONSHAREDBUCKET='
      line: 'UKMONSHAREDBUCKET=s3://{{archivebucket}}'
    tags: [dev,prod]
