- hosts: ukmonhelper
  vars:
    srcdir: /mnt/e/dev/meteorhunting/UKMON-shared/archive
  tasks:
  - name: import dev variables 
    include_vars: ../dev-vars.yml
    tags: dev
  - name: import prod variables
    include_vars: ../prod-vars.yml
    tags: prod
  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/logs exists
    file: path={{destdir}}/logs state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/website/browse/monthly exists
    file: path={{destdir}}/website/browse/monthly state=directory
    tags: [dev,prod]
  - name: Ensures {{destdir}}/website/browse/annual exists
    file: path={{destdir}}/website/browse/annual state=directory
    tags: [dev,prod]
  - name: Ensures {{destdir}}/website/browse/showers exists
    file: path={{destdir}}/website/browse/showers state=directory
    tags: [dev,prod]
  - name: Ensures {{destdir}}/website/data exists
    file: path={{destdir}}/website/data state=directory
    tags: [dev,prod]

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    with_items:
    - {src: '{{srcdir}}/website/createShwrExtracts.sh', dest: '{{destdir}}/website/', mode: '754', backup: no }
    - {src: '{{srcdir}}/website/createMthlyExtracts.sh', dest: '{{destdir}}/website/', mode: '754', backup: no }
    - {src: '{{srcdir}}/website/createReportIndex.sh', dest: '{{destdir}}/website/', mode: '754', backup: no }
    - {src: '{{srcdir}}/website/createOrbitIndex.sh', dest: '{{destdir}}/website/', mode: '754', backup: no }
    - {src: '{{srcdir}}/website/createPageIndex.sh', dest: '{{destdir}}/website/', mode: '754', backup: no }
    - {src: '{{srcdir}}/website/createSummaryTable.sh', dest: '{{destdir}}/website/', mode: '754', backup: no }
    - {src: '{{srcdir}}/website/createHistExtracts.sh', dest: '{{destdir}}/website/', mode: '754', backup: no }
    - {src: '{{srcdir}}/website/createHistShwrExtracts.sh', dest: '{{destdir}}/website/', mode: '754', backup: no }
    - {src: '{{srcdir}}/website/templates/header.html', dest: '{{destdir}}/website/templates/', mode: '644', backup: no }
    - {src: '{{srcdir}}/website/templates/footer.html', dest: '{{destdir}}/website/templates/', mode: '644', backup: no }
    - {src: '{{srcdir}}/website/templates/shwrcsvindex.html', dest: '{{destdir}}/website/templates/', mode: '644', backup: no }
    - {src: '{{srcdir}}/cronjobs/nightlyJob.sh', dest: '{{destdir}}/cronjobs/', mode: '754', backup: no }
#    - {src: '{{srcdir}}/website/static_content', dest: '{{destdir}}/website', mode: '754', backup: no }
#  - name: test s3 
#    tags: [dev,prod]
#    amazon.aws.aws_s3:
#      bucket: '{{websitebucket}}'
#      mode: get
#      object: about.html
#      dest: /tmp/test.txt
#      profile: '{{s3profile}}'