version: 0.0
os: linux
files:
  - source: archive/website/
    destination: /home/ec2-user/test/website/
  - source: archive/analysis/
    destination: /home/ec2-user/test/analysis/
  - source: ukmon_pylib/
    destination: /home/ec2-user/test/ukmon_pylib/
hooks:
  BeforeInstall:
    - location: archive/codeDeploy/before-install.sh
      timeout: 900
  AfterInstall:
    - location: archive/codeDeploy/setPermissions.sh
permissions:
  - object: /home/ec2-user/test/website
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 754
    type:
      - file
  - object: /home/ec2-user/test/analysis
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 754
    type:
      - file
